import sys, time, pathlib
from playwright.sync_api import sync_playwright
HERE = pathlib.Path(__file__).parent
TOOLBOX = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else HERE.parent / 'toolbox.js').read_text()
URL = (HERE / 'board.html').as_uri()
fails = []
def check(c, w):
    print(('PASS ' if c else 'FAIL ') + w)
    if not c: fails.append(w)
def B(page, t): return page.locator('#st-toolbox button:visible', has_text=t).first
def T(page): return page.locator('#st-toolbox').inner_text()
def log(page): return page.evaluate("() => Array.from(document.querySelectorAll('#st-toolbox pre')).filter(p => p.offsetParent).map(p => p.textContent).join('\\n')")
def busy(page): return page.evaluate("() => !!Array.from(document.querySelectorAll('#st-toolbox button')).find(b => b.offsetParent && /^Stop/.test(b.textContent))")
def wait_done(page, t=120):
    time.sleep(0.5); end = time.time() + t
    while time.time() < end:
        if not busy(page): return True
        time.sleep(0.3)
    return False
with sync_playwright() as p:
    b = p.chromium.launch(); page = b.new_page(viewport={'width': 1400, 'height': 900})
    errors = []; page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(URL + '#/DispatchBoard'); page.wait_for_selector('a.appointment')
    page.evaluate(TOOLBOX)
    B(page, 'Job Notifications').click()
    check(page.locator('#st-notify-tech').is_visible() and 'Tech One' in page.evaluate("() => document.getElementById('st-notify-tech').textContent"), 'tech picker still there by default')
    page.locator('#st-toolbox label:visible', has_text='Jobs I pick').locator('input').check()
    check(not page.locator('#st-notify-tech').is_visible() and '0 jobs picked' in T(page), 'switches to picked jobs')
    check(B(page, 'Check jobs').is_disabled(), 'check disabled with nothing picked')
    B(page, 'Pick on board').click()
    page.click('a.appointment[data-job-id="111111"]')
    page.click('.job-list tr.qa-job-901003 td')
    check(page.evaluate("() => window.opened.length") == 0, 'clicks captured while picking')
    B(page, '+ All in the list').click()
    check('3 jobs picked' in T(page) and 'Added 1 job from the Hold list' in T(page), 'whole list tab added (no duplicates)')
    page.fill('#st-toolbox input[placeholder="Or type job #s"]', '222222')
    page.locator('#st-toolbox button:visible', has_text='Add').filter(has_not_text='All').filter(has_not_text='note').first.click()
    check('4 jobs picked' in T(page) and 'Tray Cust 901004' in T(page), 'typed job added; list labels show customer')
    page.evaluate("() => { window.NOTIF = { '222222': false }; }")
    B(page, 'Check jobs').click()
    check(wait_done(page), 'check run finishes')
    lg = log(page); print(lg)
    check('Picked jobs (4) (checking only' in lg and lg.count('ON (left alone)') == 3 and '222222: already off' in lg, 'check reports each picked job')
    check(page.evaluate("() => Object.values(window.NOTIF).filter(v => v).length") == 3, 'check changed nothing')
    check('4 jobs picked' in T(page), 'check keeps the list')
    B(page, 'Turn off notifications').click()
    check('Turn OFF notifications on 4 picked jobs?' in T(page), 'confirm counts picked jobs')
    B(page, 'Yes, turn them off').click()
    check(wait_done(page), 'turn-off run finishes')
    lg = log(page); print(lg)
    check(page.evaluate("() => Object.values(window.NOTIF).every(v => !v)") and lg.count('turned off') == 3, 'notifications turned off on picked jobs')
    check('0 jobs picked' in T(page), 'done jobs come off the list')
    check(page.evaluate("() => location.hash").startswith('#/DispatchBoard'), 'back on the board')
    # Tech mode still works
    page.locator('#st-toolbox label:visible', has_text="A tech's jobs").locator('input').check()
    check(page.locator('#st-notify-tech').is_visible(), 'back to the tech picker')
    page.evaluate("() => { window.NOTIF = {}; }")
    B(page, 'Check jobs').click()
    check(wait_done(page, 150), 'tech check run finishes')
    lg = log(page); print(lg)
    check(' - Tech One (checking only' in lg and lg.count('ON (left alone)') == 8, 'tech mode checks all 8 of the tech\'s jobs')
    # Picking far down a long list must not jump the page (and still picks the job)
    B(page, 'Clear').click() if B(page, 'Clear').count() else None
    page.locator('#st-toolbox label:visible', has_text='Jobs I pick').locator('input').check()
    B(page, 'Pick on board').click()
    page.evaluate("() => document.querySelector('.job-list tr.qa-job-950055').scrollIntoView({ block: 'center' })")
    y0 = page.evaluate("() => window.scrollY")
    for j in ['950054', '950055', '950056']:
        page.click('.job-list tr.qa-job-%s td' % j)
    time.sleep(0.4)
    y1 = page.evaluate("() => window.scrollY")
    check(abs(y1 - y0) < 2 and '3 jobs picked' in T(page), 'no jump when picking deep in the list (scroll %d -> %d)' % (y0, y1))
    check(page.evaluate("() => document.activeElement === document.querySelector('.job-list table')") is False, 'the list did not take focus')
    B(page, 'Picking: ON').click()
    page.evaluate("() => { window.opened = []; }")
    page.click('.job-list tr.qa-job-950057 td')
    time.sleep(0.2)
    y2 = page.evaluate("() => window.scrollY")
    check(y2 < y1 - 200, 'without picking, the fake list jumps like the real one (test is valid): %d -> %d' % (y1, y2))
    page.evaluate("() => { window.opened = []; window.scrollTo(0, 0); }")
    # Timeline: pressing a job while picking can't start a drag
    B(page, 'Pick on board').click()
    page.evaluate("() => { window.pressed = 0; document.querySelector('a.appointment').parentElement.addEventListener('mousedown', () => window.pressed++); }")
    page.click('a.appointment[data-job-id="333333"]')
    check(page.evaluate("() => window.pressed") == 0 and '4 jobs picked' in T(page), 'timeline press swallowed while picking (no drag start)')
    B(page, 'Picking: ON').click()
    page.click('a.appointment[data-job-id="333333"]')
    check(page.evaluate("() => window.pressed") == 1, 'timeline press works normally when not picking')
    page.evaluate("() => { window.opened = []; }")

    # Highlights only show while the tool is open
    lit = lambda: page.evaluate("() => ({ bubble: getComputedStyle(document.querySelector('a.appointment[data-job-id=\"333333\"]')).outlineStyle, row: getComputedStyle(document.querySelector('.job-list tr.qa-job-950055 > td')).backgroundColor })")
    l0 = lit()
    check(l0['bubble'] == 'solid' and l0['row'] not in ('rgba(0, 0, 0, 0)', 'transparent'), 'picked jobs highlighted while Job Notifications is open')
    B(page, '← Menu').click()
    l1 = lit()
    check(l1['bubble'] != 'solid' and l1['row'] in ('rgba(0, 0, 0, 0)', 'transparent'), 'highlights gone after leaving: %s' % l1)
    B(page, 'Customer Texts').click()
    check(lit()['bubble'] != 'solid', 'no Job Notifications highlights inside Customer Texts')
    page.evaluate("() => { const b = Array.from(document.querySelectorAll('#st-toolbox button')).find(b => /Menu/.test(b.textContent) && b.offsetParent); if (b) b.click(); }")
    B(page, 'Job Notifications').click()
    check(lit()['bubble'] == 'solid' and '4 jobs picked' in T(page), 'highlights and list come back on return')
    page.locator('#st-toolbox label:visible', has_text="A tech's jobs").locator('input').check()
    check(lit()['bubble'] != 'solid', "no highlights in A tech's jobs mode")

    # Leaving the tool turns picking off
    page.locator('#st-toolbox label:visible', has_text='Jobs I pick').locator('input').check()
    B(page, 'Pick on board').click()
    B(page, '← Menu').click()
    page.click('a.appointment[data-job-id="111111"]')
    check(page.evaluate("() => window.opened.length") == 1, 'picking turns off when leaving the tool')
    page.evaluate("() => window.__stToolbox.close()")
    check(errors == [], 'no page errors: %s' % errors)
    b.close()
print('\n%d FAILED' % len(fails) if fails else '\nALL PASSED')
for f in fails: print(' - ' + f)
sys.exit(1 if fails else 0)
